name: 3-Security-Scan-SAST-SCA-SBOM

# This Workflow will submit the application artifact to Veracode for SAST and SCA scan
# It will run manually or automatically after 1-Checkout-Build-Artifact.yml completes

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["2-Dockerize-Publish"]
    types:
      - completed

jobs:
  Security-Scan-SAST-SCA:
    runs-on: ubuntu-latest
    steps:
        
# Download the most recent build artifact from the 1-Checkout-Build-Artifact worfklow.
      
    - name: Download Checkout-Build-Artifact Workflow Artifact
      uses: qiwi-forks/action-download-artifact@v2
      with: 
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: 1-Checkout-Build-Artifact.yml
        name: VeraDemoDotNetCoreAppArtifact
        skip_unpack: true
      continue-on-error: false
    
    - name: List folder contents for visual to confirm artifact file exists
      run: |
        ls -la
    
# Use the UploadAndScan action to submit the artifact for scanning
    - name: Veracode Upload and Scan Action Step
      uses: veracode/veracode-uploadandscan-action@master
      id: upload_and_scan
      with:
        appname: 'VeraDemo-DotNetCore-GitHub'
        createprofile: false
        version: '${{ github.run_id }}'
        criticality: Medium
        filepath: 'VeraDemoDotNetCoreAppArtifact.zip'
        vid: '${{ secrets.VERACODE_API_ID }}'
        vkey: '${{ secrets.VERACODE_API_KEY }}'
      continue-on-error: true

  # Veracode CLI against the container       
  Container-Inspection-SBOM:
    runs-on: ubuntu-latest
    steps:
      - name: Veracode Container Scanner
        run: |
          mkdir tmp
          cd tmp
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          export VERACODE_API_KEY_ID=${{ secrets.VERACODE_API_ID }}
          export VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_KEY }}
          ls -la
          ./veracode scan --source /home/runner/work/verademo-dotnetcore/verademo-dotnetcore --type directory --format table -o IssuesSource.txt
          ./veracode sbom --source veracodedemolabs/verademo-dotnetcore-github:latest --type image --format table -o SBOM.txt

# Store security artifacts
      - name: Upload security artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: SecurityArtifacts
          path: ./tmp/*.txt     

# Running SCA Agent against Repo          
  SCA-Agent-Scan-Resuls-Import:
    runs-on: ubuntu-latest
    steps:
    # Running Software Composition Analysis Agent against the local repo and the container
      # Checkout code
      - uses: actions/checkout@v3
      - name: List folder contents for visual to confirm artifact file exists
        run: |
          ls -la
    
      #SCA Agent against repo
      - name: Veracode SCA Agent Dependency Scanning
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.0.65
        with:
          github_token: ${{ github.token }}
          update_advisor: true
          create-issues: true
        # A path within the repository where the build definition starts
          path: app
        # Run the SRCCLR with the `--allow-dirty` option
          allow-dirty: true 

      - name: Upload artifact with SCA app and container issues for this build
        uses: actions/upload-artifact@v3.1.1
        with:
           name: SCA-Issues-VeraDemoDotNetCore-${{ github.run_id }}
           path: "*.json"       
